create table if not exists users
(
    id            int primary key generated by default as identity,
    login         varchar(50)             not null,
    password      varchar(200)            not null,
    first_name    varchar(50)             not null,
    last_name     varchar(50)             not null,
    year_of_birth varchar(20)             not null,
    phone_number  varchar(50)             not null,
    email         varchar(50) unique      not null,
    role_id       int                     references role (id) on delete set null,
    isProject     boolean   default false not null,
    isTask        boolean   default false not null,
    department    varchar(50)             not null,
    post          varchar(50)             not null,
    creation      timestamp default now(),
    update        timestamp default now()
);
drop table users;

insert into users(first_name, last_name, phone_number, email, role, status_role, post, department, password,
                  year_of_birth)
values ('Ivan', 'Ivanov', '22222', 'ivan@ivan.ru', 'ADMIN', 'ACTIVE', 'DIRECTOR', 'SALES', '123', '26/07/1987');
insert into users(first_name, last_name, phone_number, email, role, status_role, post, department, password,
                  year_of_birth)
values ('Bob', 'Tomson', '11111', 'bob@tomson.ru', 'EMPLOYEE', 'ACTIVE', 'MANAGER', 'SALES', '123', '10/11/1980');

create table if not exists company
(
    id                 int primary key generated by default as identity,
    name               varchar(50)            not null,
    description        varchar(2000)          not null,
    company_type       varchar(50)            not null,
    website            varchar(50) unique     not null,
    address            varchar(50)            not null,
    phone_number       varchar(50)            not null,
    email              varchar(50)            not null,
    independent_search boolean   default true not null,
    users_id           int                    references users (id) on delete set null,
    creation           timestamp default now(),
    update             timestamp default now()
);

drop table client;

create table role
(
    id          int primary key generated by default as identity,
    name        varchar(50)          not null,
    description varchar(2000)        not null,
    custom      boolean default true not null,
    isACTIVE    boolean default true not null
);
drop table role;
create table if not exists type_company
(
    id          int primary key generated by default as identity,
    name        varchar(50)          not null,
    description varchar(2000)        not null,
    custom      boolean default true not null,
    company_id  int                  references users (id) on delete set null
);
drop table type_company;
create table if not exists post
(
    id          int primary key generated by default as identity,
    users_id    int                  references users (id) on delete set null,
    name        varchar(50)          not null,
    description varchar(2000)        not null,
    custom      boolean default true not null
);
create table if not exists department
(
    id          int primary key generated by default as identity,
    users_id    int                  references users (id) on delete set null,
    name        varchar(50)          not null,
    description varchar(2000)        not null,
    custom      boolean default true not null

);
drop table department;


create table if not exists project
(
    id           int primary key generated by default as identity,
    project_name varchar(50)            not null,
    description  varchar(2000)          not null,
    custom       boolean   default true not null,
    creation     timestamp default now(),
    update       timestamp default now(),
    users_id     int                    references users (id) on delete set null,
    company_id   int                    references company (id) on delete set null
);
create table if not exists task
(
    id          int primary key generated by default as identity,
    name        varchar(50)   not null,
    description varchar(5000) not null,
    creation    timestamp default now(),
    update      timestamp default now(),
    users_id    int           references users (id) on delete set null,
    company_id  int           references company (id) on delete set null
);

create table if not exists user_role
(
    users_id int references users (id) on delete set null,
    role_id  int references role (id) on delete set null

);