create table if not exists users
(
    id            int primary key generated by default as identity,
    first_name    varchar(50)  not null,
    last_name     varchar(50)  not null,
    phone_number  varchar(50)  not null,
    email         varchar(50)  not null,
    role          varchar(50)  not null,
    status_role   varchar(50)  not null,
    post          varchar(50)  not null,
    departament   varchar(50)  not null,
    password      varchar(200) not null,
    year_of_birth varchar(20)  not null,
    creation      timestamp default now(),
    update        timestamp default now()
);
drop table users;

insert into users(first_name, last_name, phone_number, email, role, status_role, post, departament, password, year_of_birth)
values ('Ivan', 'Ivanov', '22222', 'ivan@ivan.ru', 'ADMIN', 'ACTIVE', 'DIRECTOR', 'SALES','123','26/07/1987');
select * from users;